// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: service.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GrpcRestServiceClient is the client API for GrpcRestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrpcRestServiceClient interface {
	SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*SayHelloResponse, error)
}

type grpcRestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcRestServiceClient(cc grpc.ClientConnInterface) GrpcRestServiceClient {
	return &grpcRestServiceClient{cc}
}

func (c *grpcRestServiceClient) SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*SayHelloResponse, error) {
	out := new(SayHelloResponse)
	err := c.cc.Invoke(ctx, "/grpc_rest.v1.GrpcRestService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcRestServiceServer is the server API for GrpcRestService service.
// All implementations must embed UnimplementedGrpcRestServiceServer
// for forward compatibility
type GrpcRestServiceServer interface {
	SayHello(context.Context, *SayHelloRequest) (*SayHelloResponse, error)
	mustEmbedUnimplementedGrpcRestServiceServer()
}

// UnimplementedGrpcRestServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGrpcRestServiceServer struct {
}

func (UnimplementedGrpcRestServiceServer) SayHello(context.Context, *SayHelloRequest) (*SayHelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGrpcRestServiceServer) mustEmbedUnimplementedGrpcRestServiceServer() {}

// UnsafeGrpcRestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcRestServiceServer will
// result in compilation errors.
type UnsafeGrpcRestServiceServer interface {
	mustEmbedUnimplementedGrpcRestServiceServer()
}

func RegisterGrpcRestServiceServer(s grpc.ServiceRegistrar, srv GrpcRestServiceServer) {
	s.RegisterService(&GrpcRestService_ServiceDesc, srv)
}

func _GrpcRestService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcRestServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_rest.v1.GrpcRestService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcRestServiceServer).SayHello(ctx, req.(*SayHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GrpcRestService_ServiceDesc is the grpc.ServiceDesc for GrpcRestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrpcRestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_rest.v1.GrpcRestService",
	HandlerType: (*GrpcRestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _GrpcRestService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
