// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: grpc-rest-multipart-server.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GrpcRestMultipartServiceClient is the client API for GrpcRestMultipartService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrpcRestMultipartServiceClient interface {
	SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*SayHelloResponse, error)
}

type grpcRestMultipartServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcRestMultipartServiceClient(cc grpc.ClientConnInterface) GrpcRestMultipartServiceClient {
	return &grpcRestMultipartServiceClient{cc}
}

func (c *grpcRestMultipartServiceClient) SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*SayHelloResponse, error) {
	out := new(SayHelloResponse)
	err := c.cc.Invoke(ctx, "/grpc_rest.v2.GrpcRestMultipartService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcRestMultipartServiceServer is the server API for GrpcRestMultipartService service.
// All implementations must embed UnimplementedGrpcRestMultipartServiceServer
// for forward compatibility
type GrpcRestMultipartServiceServer interface {
	SayHello(context.Context, *SayHelloRequest) (*SayHelloResponse, error)
	mustEmbedUnimplementedGrpcRestMultipartServiceServer()
}

// UnimplementedGrpcRestMultipartServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGrpcRestMultipartServiceServer struct {
}

func (UnimplementedGrpcRestMultipartServiceServer) SayHello(context.Context, *SayHelloRequest) (*SayHelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGrpcRestMultipartServiceServer) mustEmbedUnimplementedGrpcRestMultipartServiceServer() {
}

// UnsafeGrpcRestMultipartServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcRestMultipartServiceServer will
// result in compilation errors.
type UnsafeGrpcRestMultipartServiceServer interface {
	mustEmbedUnimplementedGrpcRestMultipartServiceServer()
}

func RegisterGrpcRestMultipartServiceServer(s grpc.ServiceRegistrar, srv GrpcRestMultipartServiceServer) {
	s.RegisterService(&GrpcRestMultipartService_ServiceDesc, srv)
}

func _GrpcRestMultipartService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcRestMultipartServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_rest.v2.GrpcRestMultipartService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcRestMultipartServiceServer).SayHello(ctx, req.(*SayHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GrpcRestMultipartService_ServiceDesc is the grpc.ServiceDesc for GrpcRestMultipartService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrpcRestMultipartService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_rest.v2.GrpcRestMultipartService",
	HandlerType: (*GrpcRestMultipartServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _GrpcRestMultipartService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc-rest-multipart-server.proto",
}
